create table
  public.users (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    name text[] null,
    company text null,
    phone numeric null,
    email text[] null,
    constraint users_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.transcripts (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    meet_date timestamp without time zone null,
    fireflies_id text not null,
    action_items text null,
    bullet_gist text null,
    gist text null,
    overview text null,
    shorthand_bullet text null,
    speakers bigint[] null,
    constraint transcripts_pkey primary key (id),
    constraint transcripts_fireflies_id_key unique (fireflies_id)
  ) tablespace pg_default;

  create table
  public.sentences (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    user_id bigint not null,
    transcript_id bigint not null,
    start_time real null,
    end_time real null,
    sentiment text null,
    text text null,
    question text null,
    task text null,
    constraint sentences_pkey primary key (id),
    constraint sentences_transcript_id_fkey foreign key (transcript_id) references transcripts (id),
    constraint sentences_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;